version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0

# YAML anchors for some common/repeated values
x-common-params:
  - &xcode-version "11.2.1"
  - &podspec "WordPressShared.podspec"
  - &on-tags-only
      tags:
        only: /.*/
      branches:
        ignore: /.*/

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Test
          xcode-version: *xcode-version
          workspace: WordPressShared.xcworkspace
          scheme: WordPressShared
          device: iPhone 11
          ios-version: "13.2.2"
          bundle-install: true
          pod-install: true
      - ios/validate-podspec:
          name: Validate Podspec
          xcode-version: *xcode-version
          podspec-path: *podspec
          bundle-install: true
