# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#3.1.0
  env: &common_env
    IMAGE_ID: xcode-15.0.1

# This is the default pipeline – it will build and test the pod
steps:
  ########################
  # Validate Swift Package
  ########################
  - label: "🔬 Validate Swift Package"
    key: "test"
    command: validate_swift_package
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - .build/logs/*.log
      - .build/derived-data/Logs/**/*.xcactivitylog

  #################
  # Validate Podspec
  #################
  - label: "🔬 Validate Podspec"
    key: "validate"
    command: validate_podspec --patch-cocoapods
    env: *common_env
    plugins: *common_plugins
    artifact_paths: ".build/logs/*.log"

  #################
  # Lint
  #################
  - label: "🧹 Lint"
    key: "lint"
    command: lint_pod
    env: *common_env
    plugins: *common_plugins

  - label: ":swift: SwiftLint"
    key: "swiftlint"
    command: run_swiftlint --strict
    plugins: *common_plugins
    notify:
      - github_commit_status:
          context: "SwiftLint"
    agents:
      queue: "default"

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: .buildkite/commands/publish-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - test
      - validate
      - lint
      - swiftlint
    if: build.tag != null
