# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
  - &bash_cache automattic/bash-cache#2.9.0
  env: &common_env
    IMAGE_ID: xcode-14

# This is the default pipeline – it will build and test the pod
steps:
  ################
  # Build and Test
  ################
  - label: "🧪 Build and Test iOS"
    key: "test"
    command: |
      build_and_test_pod
    env: *common_env
    plugins: *common_plugins
    artifact_paths: ".build/logs/*.log"

  #################
  # Validate Podspec
  #################
  - label: "🔬 Validate Podspec"
    key: "validate"
    command: |
      validate_podspec
    env: *common_env
    plugins: *common_plugins
    artifact_paths: ".build/logs/*.log"

  #################
  # Lint
  #################
  - label: "🧹 Lint"
    key: "lint"
    command: |
      lint_pod
    env: *common_env
    plugins: *common_plugins

  #################
  # Check Regex
  #################
  - label: ":face_with_monocle: Check Regular Expressions"
    key: "check-regex"
    command: ".buildkite/check_regex.sh"
    env: *common_env
    plugins: *common_plugins

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: |
      .buildkite/publish-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test"
      - "validate"
      - "lint"
      - "check-regex"
    if: build.tag != null
