# frozen_string_literal: true

default_platform(:ios)

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'WordPressShared',
      build_for_testing: true, # DEBUG: Simulate how WordPress does things
      prelaunch_simulator: true,
      buildlog_path: File.join(__dir__, '.build', 'logs'),
      derived_data_path: File.join(__dir__, '.build', 'derived-data')
    )
  end
end
