# frozen_string_literal: true

default_platform(:ios)

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    xcodebuild(
      scheme: 'WordPressShared',
      xcargs: '-resolvePackageDependencies'
    )
    run_tests(
      package_path: '.',
      scheme: 'WordPressShared',
      device: 'iPhone 14',
      prelaunch_simulator: true,
      buildlog_path: File.join(__dir__, '.build', 'logs'),
      derived_data_path: File.join(__dir__, '.build', 'derived-data')
    )
  end
end
