name: ☢️ Danger

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  dangermattic:
    uses: Automattic/dangermattic/.github/workflows/reusable-run-danger.yml@v1.0.0
    secrets:
      github-token: ${{ secrets.DANGERMATTIC_GITHUB_TOKEN }}
